name: ESLint

on: pull-request

jobs:
  eslint:
    runs-on: ubunutu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Install modules
       run: npm ci
     - name: Run ESLint
       run: npm run check
